## Date Time 



In [ ]:
from datetime import datetime , timedelta


In [ ]:
curr_time  = datetime.now()
print("time now", curr_time, ',', curr_time.time() )


In [ ]:
from datetime import timedelta

print ("now", curr_time, "\nyesterday " , curr_time - timedelta(days=1))

In [ ]:
t1 = datetime(2017,10,19, 9,30, 0, 0)
print(t1)
t2 = t1 + timedelta(hours=8)
print(t2)
# Find number of minutes between 9:30 to 5:30 

d = t2- t1
diff_mins = d.seconds/60
print("Time difference in minutes =" , diff_mins, ' mins')

Find number of minutes from time object 

In [ ]:
from datetime import time
t3 = time(9,30,0,0) 
t4 = time(17,30, 0, 0)
print(t3, t4)
# can't do this t3 -t4
td3 = timedelta(hours = t3.hour, minutes = t3.minute, seconds = t3.second, milliseconds = 0, microseconds=0)
td4 = timedelta(hours = t4.hour, minutes = t4.minute, seconds = t4.second, milliseconds = 0, microseconds=0)

print ("diff:", (td4 - td3).total_seconds()/60)

## Random 

In [1]:
import random

# Sample 5 numbers from range 10-20
random.sample(range(10,20), 5)

[19, 13, 12, 15, 18]

In [2]:
# generate a random number in range 0-1
random.uniform(1,2)

1.5164922860559122

In [3]:
[random.uniform(1,2) for x in range(5)]

[1.9398849019153057,
 1.3318815158754858,
 1.9905150101492457,
 1.6570143428890325,
 1.353320717322462]

In [1]:
import numpy as np
print(np.random.uniform())
print(np.random.uniform(2,3))
print(np.random.uniform(2,3,5))
print(np.random.randn(5,2))

0.7383707623532517
2.059696557538261
[ 2.98154041  2.14647614  2.21116717  2.41528171  2.39085686]
[[-0.79641075 -0.54093435]
 [ 0.35700015 -1.38815003]
 [-0.31335401 -1.05004409]
 [ 0.60440578 -1.34107467]
 [-0.1640396  -0.89449821]]


In [ ]:
[x for x in range(3,5)]

   ## Lists
   Can have elements of different types. Reference : http://www.physics.nyu.edu/pine/pymanual/html/chap3/chap3_arrays.html
   

In [6]:
empty_list = []
l = [1,2,'h',"hello"]
print(empty_list, l, l[3])

[] [1, 2, 'h', 'hello'] hello


In [9]:
# concatenate list 
print (l + l )
#slice list 
print (l[:2], l[2:])

[1, 2, 'h', 'hello', 1, 2, 'h', 'hello']
[1, 2] ['h', 'hello']


## Tuples = Immutable lists 


In [14]:
c = (1, 3, 'c', "kkk")
print(c)
#c[2] = 5 # ERROR: Can't modify tuple

(1, 3, 'c', 'kkk')



## Multi dimensional Array

In [19]:
a = [[1,2],[3,4], [5,6]]
print(a, len(a), len(a[1]))

print(a[2], a[2][1])

[[1, 2], [3, 4], [5, 6]] 3 2
[5, 6] 6


### Numpy Array

In [35]:
import numpy as np

na = np.array([3,6,8])
print(na)

na1 = np.linspace(0,10, 5)
na2 = np.logspace(0,9,5) # 5 points in range 10^0 to 10^9
na3 = np.arange(0,10,2)
print(na1, na2, na3)

na4 = np.zeros(4, dtype=int)
na5 = np.ones(4, dtype=int)

print(na4, na5)

[3 6 8]
[  0.    2.5   5.    7.5  10. ] [  1.00000000e+00   1.77827941e+02   3.16227766e+04   5.62341325e+06
   1.00000000e+09] [0 2 4 6 8]
[0 0 0 0] [1 1 1 1]


### Numpy: Multi dimensional array 

In [44]:
 a = np.ones((3,4), dtype=float)
print(a)
c = np.arange(6)
c1 = np.reshape(c, (2,3))
print(c,'\n', c1)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[0 1 2 3 4 5] 
 [[0 1 2]
 [3 4 5]]


In [45]:
#indexing array
c1[1][2]

5

### Dictionaries

In [48]:
weird = {"tank":52, 846:"horse", "bones":[23, "fox", "grass"], "phrase":"I am here"}
e = weird['tank']
print (weird.keys(), weird.values())


dict_keys(['tank', 'phrase', 'bones', 846]) dict_values([52, 'I am here', [23, 'fox', 'grass'], 'horse'])


# Bitwise operators

Binary number written with prefix 0b. 



In [ ]:
print(0b11) ; x=0b111; print(x)

In [ ]:
bin(3)

Bitwise operators : operators <<, >>, &, |, ~, and ^ 

In [ ]:
print('Left shift 10<<2 = ', 10<<2, '; right shift 10>>2 = ', 10>>2)

In [ ]:
print("bitwise AND 10&1 = ", 10 & 1, "; OR 10|1 = ", 10|1, "; Complement ~10 = ", ~10, " ; XOR 10 ^ 1 = ", 10^1)

# Count number of 1 bits in an int

In [ ]:
def one_bits(n):
    print (n, ', in binary = ', bin(n) )
    cnt=0
    while (n > 0): 
        if (n & 1 == 1):
            cnt+=1
        n = n>>1
    return cnt

def one_bits2(n):
    cnt = 0 
    while (n > 0):
        n &= (n-1)
        cnt+=1
    return cnt

In [ ]:
one_bits(11), one_bits2(11)

In [2]:
print(9&8, 8&7)

8 0


Extract the lowest set bit

In [2]:
x = 12
y = x & ~(x-1)
print (bin(x) , bin(y), x^y, bin(x^y)) 

0b1100 0b100 8 0b1000


# Deque in python 

In [9]:
from collections import deque
d = deque([1,2,3,4])

print (d)
for x in d:
    print (x)
print(d.pop(), d)

deque([1, 2, 3, 4])
1
2
3
4
4 deque([1, 2, 3])


### Sets in python 

In [3]:
a = {2,3,3}
a

{2, 3}

In [6]:
b = {3,3,3,4,6,7,1,2}
b

{1, 2, 3, 4, 6, 7}

In [8]:
a.intersection(b)

{2, 3}

In [33]:
import random

#Merge sorted arrays
def merge(s1, s2):
    i = j = 0 ; 
    while(i < len (s1) and j < len(s2)):
        if(s1[i] == s2[j]):
            print(s1[i])
            i+=1
            j+=1
        elif s1[i]<s2[j]:
            i+=1
        else:
            j+=1
    
a1 = random.sample(range(10,20), 5)
a2 = random.sample(range(5,25), 10)
a1.sort()
a2.sort()

print (a1, a2)
merge(a1, a2)

[11, 13, 14, 18, 19] [5, 9, 11, 13, 14, 17, 19, 20, 23, 24]
11
13
14
19


In [26]:
a1.sort()
a1

[10, 12, 13, 14, 15, 16, 17, 18]

## Purge array of