In [2]:
import numpy as np 

a = np.random.randn(5) # 5 gaussian variables in a

In [4]:
print(a)

[ 1.40048158 -1.01506008 -0.34480529  1.17663168  1.87942489]


In [7]:
print(a.shape) # Rank 1 array , which is neither a row or a column vector 


(5,)


In [9]:
print (a.T)

[ 1.40048158 -1.01506008 -0.34480529  1.17663168  1.87942489]


In [10]:
print(np.dot(a, a.T))

8.02728630981


In [18]:
# instead use a with shape (5,1) when coding NN 
a = np.random.randn(5,1) # Column vector 
print(a)
print (a.shape)

[[ 1.01239202]
 [ 0.11618992]
 [-0.62451115]
 [-1.72999328]
 [ 1.67465077]]
(5, 1)


In [13]:
print(a.T)

[[ 1.3026669  -0.5628661   0.61173229  0.3974514  -0.45557304]]


In [15]:
print(np.dot(a, a.T))

[[ 1.69694106 -0.73322703  0.79688341  0.51774678 -0.59345992]
 [-0.73322703  0.31681824 -0.34432337 -0.22371192  0.25642662]
 [ 0.79688341 -0.34432337  0.3742164   0.24313385 -0.27868874]
 [ 0.51774678 -0.22371192  0.24313385  0.15796761 -0.18106814]
 [-0.59345992  0.25642662 -0.27868874 -0.18106814  0.20754679]]


## Lets try row-vector dot col-vector

In [20]:
a = np.random.randn(1,5)
print(a)
print(a.shape)

[[-0.20011264 -1.36466987 -1.29315034 -0.53682214 -0.17205009]]
(1, 5)


In [21]:
print(np.dot(a, a.T))

[[ 3.89238599]]


In [24]:
 # Reshape a rank 1 array 
arr = np.random.randn(5)
print (arr.shape, arr.reshape(5,1).shape)

(5,) (5, 1)
