In [3]:
[x for x in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
import random
random.sample(range(10),5)

[5, 9, 4, 3, 6]

In [3]:
import numpy as np
np.random.uniform(-1,1,5)

array([ 0.34288874,  0.49009124,  0.91175526,  0.74727425, -0.53137406])

In [3]:
np.random.rand(3,10)

array([[ 0.16784888,  0.01399846,  0.73774109,  0.74335286,  0.60789388,
         0.73730288,  0.49102883,  0.93001935,  0.52747404,  0.27986856],
       [ 0.76620195,  0.65082592,  0.89762379,  0.87619895,  0.43214662,
         0.7015976 ,  0.34058573,  0.277152  ,  0.09236506,  0.33801089],
       [ 0.0643036 ,  0.83528474,  0.3641297 ,  0.15305575,  0.435848  ,
         0.39550501,  0.63922666,  0.29693217,  0.88985781,  0.8972056 ]])

In [6]:
a = np.random.randn(3,2)
print(a)
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[[ 0.17713707 -1.48963985]
 [-0.14360237 -0.39622363]
 [-0.00295823  0.6669378 ]]
[ 0.03057648 -1.21892567]
[-1.31250278 -0.53982599  0.66397958]


In [8]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
B.shape

(4, 1)

In [1]:
xrange(10)


NameError: name 'xrange' is not defined